language: python
python:
  - '2.7'
  - '3.6'
#  - '3.7'
#  - '3.8'

addons:
  apt:
    packages:
      - libssl-dev
      - libc6-i386

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl
    - LISP=allegro
    - LISP=abcl
    - LISP=ccl-bin
    - LISP=clisp
    - LISP=cmu-bin
    - LISP=ecl

matrix:
  allow_failures:
    # Only plan to support 64-bit SBCL, but check compatilibity issues on other
    # distributions.
    - env: LISP=allegro
    - env: LISP=abcl
    - env: LISP=ccl-bin
    - env: LISP=clisp
    - env: LISP=cmu-bin
    - env: LISP=ecl

install:
  #
  # Install lisp environment.
  #
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  #- ./script/cl_travis_install.sh
  #- ./script/install_lisp_dependencies.sh
  - ros install genelkim/ttt
  - ros install genelkim/cl-util
  - ros install genelkim/ulf-lib
  - ln -s $(pwd) ~/.roswell/local-projects/ulf2english

  #
  # Install conda-based python environment.
  #
  - sudo apt update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # Useful for debugging any issues with conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment

  # Install python dependences
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      ./script/install-pattern-en.sh;
    else
      pip install pattern;
    fi

cache:
  directories:
    # Cache roswell
    - $HOME/.roswell

script
  - ros -l runtest.lisp
  #- cl -e '(load "runtest")'

